### GET request to example server
GET http://localhost:8080

###
GET http://localhost:8080/api/v1/software-engineers/3

###
POST http://localhost:8080/api/v1/software-engineers
Content-Type: application/json

{
  "name": "jamila",
  "techstack": "java ,spring "
}
###
DELETE http://localhost:8080/api/v1/software-engineers/1
###
PUT http://localhost:8080/api/v1/software-engineers/2
Content-Type: application/json

{
  "name": "John Doe",
  "techStack": "Java, Spring Boot, PostgreSQL"
}